<a href="https://colab.research.google.com/github/itsCiandrei/LinearAlgebra_2ndSem/blob/main/Assignment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Linear Algebra for ChE

##Laboratory 4: Matrices

###Objectives

##Discussion

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline 

###Matrices

######In mathematics, a matrix is a rectangular arrangement of numbers, symbols, or expressions into rows and columns. It is commonly used in solving a series of linear equations with different numbers of variables. In addition, matrices are used to provide quick estimations of more complex equations. We used the text typesetting feature of google collab for formatting the output. Here, the series of equations were presented in LaTeX form. The student follows the given program format for A and B to achieve C's product. However, for C, the students introduced another independent variable, making four independent variables with different coefficients. Moreover, the equations inside A, B, and C were now presented into their matrix form, which was arranged based on their variable but represented only by their numerical coefficient. A is a system with 2 equations and 2 parameters. On the other hand, systme B has 3 equations with 3 parameters. And lastly, system C consists of 3 equations with 4 parameters.

$$
A = \left\{
    \begin{array}\
        x + y \\ 
        4x - 10y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        x+y+z \\ 
        3x -2y -z \\
        -x + 4y +2z
    \end{array}
\right.\\ 
C = \left\{
  \begin{array}\
  2w-3x+y+5z\\
  w+2x-2y-4z\\
  3w+x+y-3z\\
  \end{array}\
\right. \\
$$


$$
A=\begin{bmatrix} 1 & 1 \\ 4 & {-10}\end{bmatrix} \\
B=\begin{bmatrix} 1 & 1 & 1 \\ 3 & -2 & -1 \\ -1 & 4 & 2\end{bmatrix}\\
C =\begin{bmatrix} 2 & -3 & 1 & 5 \\ 1 & 2 & -2 & -4 \\ 3 & 1 & 1 & -3\end{bmatrix}
$$


##Declaring Matrices

#####In the previous part of this activity, students could change the LaTeX form of numerous linear equations into the matrix. Matrix A consists of different numbers or entities called the elements of a matrix, and it was arranged based on rows and columns. The subscript i signifies the row, while subscript j signifies the column of the matrices. The students were able to create different types of matrices with different dimensions and identify the shape or also known as the dimension of the matrices, and even its rank. 
 

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$


In [3]:
def describe_mat(matrix):
  print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [4]:
## Declaring a 2 x 2 matrix
R = np.array([
    [2, 1],
    [2, 3]
])
describe_mat(R)
R.shape

Matrix:
[[2 1]
 [2 3]]

Shape:	(2, 2)
Rank:	2



(2, 2)

In [5]:
J = np.array([
    [2,1,3],
    [4,3,1]
])
describe_mat(J)
J.shape

Matrix:
[[2 1 3]
 [4 3 1]]

Shape:	(2, 3)
Rank:	2



(2, 3)

In [7]:
M = np.array([3,4,5,6,7])
describe_mat(M)

Matrix:
[3 4 5 6 7]

Shape:	(5,)
Rank:	1



###According to Matrices

#####There are various ways how to classify the type of matrices. In this laboratory activity, the students classify it in two ways, the first is in terms of shape or dimension, and the other is in terms of its elements.

####According to Shape

#####The matrices are classified in terms of their dimensions. The types of matrices according to its dimension are the following: Declaring row matrix, declaring column matrix, and square matrix.

####Declaring Row Matrix

#####A row matrix is also known as a single row matrix. By referring to its name, it's evident that this matrix type only consists of one row, but the number of columns could be greater than one. Thus, its dimension could be written as '1 x n' wherein n is the number of columns. The students were able to create a row matrix having more than 1 column. In line with that, they could differentiate the difference between row and non-row matrices.

In [13]:
row_mat_1D = np.array([
                       6,6,6
])
row_mat_2D = np.array([
                    [1,-2,7,21],[2,3,1,4]   
])
describe_mat(row_mat_1D)
describe_mat(row_mat_2D)

Matrix:
[6 6 6]

Shape:	(3,)
Rank:	1

Matrix:
[[ 1 -2  7 21]
 [ 2  3  1  4]]

Shape:	(2, 4)
Rank:	2



####Declaring Column Matrix

#####If row martix is a type of matrix which consist of only single row, column matrix on the other hand is a matrix consists of only one column with more than one row. Its dimension is represented as 'n x 1' where n is the number of rows. The student were able to create a 3x1 column matrix.

In [10]:
col_mat = np.array([
        [2],[3],[7]
])
describe_mat(col_mat)

Matrix:
[[2]
 [3]
 [7]]

Shape:	(3, 1)
Rank:	2



###Square Matrix

#####The last type of matrix, according to its shape, is the square matrix. A square matrix is also known as a 'n x n' matrix having the same columns and rows. One of its applications is to solve quadratic equations having two different variables. For this part, the student formulated a program about square and non-square matrix, and it identifies if the matrix is square or non-square by printing the text "True" or "False."

In [ ]:
def describe_mat(matrix):
  is_square = True if matrix.shape[0] == matrix.shape[1] else False
  print(f'Matrix:\n {matrix} \n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs.Square:{is_square}\n')

In [12]:
square_mat = np.array([
                       [1,4,3,2],
                       [2,4,6,1],
                       [7,8,9,-1],
                       [3,1,-4,23]
])

non_square_mat = np.array([
                           [-2,2,0],
                           [1,9,7]
])
describe_mat(square_mat)
describe_mat(non_square_mat)

Matrix:
[[ 1  4  3  2]
 [ 2  4  6  1]
 [ 7  8  9 -1]
 [ 3  1 -4 23]]

Shape:	(4, 4)
Rank:	2

Matrix:
[[-2  2  0]
 [ 1  9  7]]

Shape:	(2, 3)
Rank:	2



###According to element values

#####The matrices are classified in terms of their elements. The types of matrices according to its identities are the following: Null matrix, zero matrix, ones matrix, identity matrix, upper and lower triangular matrix.

####Null Matrix

#####A null matrix is the type of matrix wherein it has no elements at all. It contains a missing value and has zero numbers of rows and columns. The students were able to produce an output of both null and not-null matrices. In addition to that, the not-null matrix is not an example of a square matrix.

In [ ]:
def describe_mat(matrix):
  if matrix.size > 0:
    is_square = True if matrix.shape[0] == matrix.shape[1] else False
    print(f'Matrix:\n {matrix} \n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs.Square:{is_square}\n')
  else:
    print('Matrix is NULL')

In [15]:
null_mat=np.array([])

notnull_mat = np.array([
                      [2,3,1],
                      [1,3,2]
])

describe_mat(null_mat)
describe_mat(notnull_mat)

Matrix:
[]

Shape:	(0,)
Rank:	1

Matrix:
[[2 3 1]
 [1 3 2]]

Shape:	(2, 3)
Rank:	2



###Zero Matrix

#####A zero matrix is a type of matrix wherein the entries of all the elements on rows and columns are zero. Zero matrices can be identified as an additive group in operating on matrices. After running the program, the students created a zero matrix with different dimensions.

In [16]:
zero_mat_row = np.zeros((2,3))
zero_mat_sqr = np.zeros((3,3))
zero_mat_rct = np.zeros((3,2))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')

Zero Row Matrix: 
[[0. 0. 0.]
 [0. 0. 0.]]
Zero Square Matrix: 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Zero Rectangular Matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


###Ones Matrix

#####The ones matrix is just the same as the zero matrices; however, the difference between the two is that the elements of this type of matrix are only integer 1. After running the program, the students created a zero matrix with different dimensions.

In [17]:
ones_mat_row = np.ones((2,3))
ones_mat_sqr = np.ones((3,3))
ones_mat_rct = np.ones((3,2))

print(f'ones Row Matrix: \n{ones_mat_row}')
print(f'ones Square Matrix: \n{ones_mat_sqr}')
print(f'ones Rectangular Matrix: \n{ones_mat_rct}')

ones Row Matrix: 
[[1. 1. 1.]
 [1. 1. 1.]]
ones Square Matrix: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
ones Rectangular Matrix: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]


####Diagonal Matrix

#####Another type of square matrix is called the diagonal matrix, wherein the principal diagonal elements of a particular matrix are non-zero digits and the rest of the elements are zero. In this part of the activity, the students could program a diagonal matrix in various ways. For example, the first is by programming the matrix manually, and the other is by using the function np.diag.

In [18]:
np.array([
      [1,0,0],
      [0,2,0],
      [0,0,3]    
])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [19]:
m = np.diag([1,2,3,5,1])
m.shape[0] == m.shape[1]
m

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 5, 0],
       [0, 0, 0, 0, 1]])

###Identity Matrix

#####An identity matrix is a special type of diagonal matrix where the values of the principal diagonal of a system or matrix are only the integer 1, and the rest are zero. Moreover, the students were able to produce an output regarding the identity matrix. Like on diagonal matrix, there are two ways to create this type of matrix: first is by manually typing the elements of the identity matrix, and; second is using the function np.identity.

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

##Upper Triangular Matrix

#####The upper triangular matrix is one of the classifications of the triangle matrix. A triangle matrix wherein the entries below the main diagonal of a particular matrix is equal to zero. On the other hand, the upper part is pure non-zero elements. For instance, in this part of the activity, the students were able to program an upper triangular matrix in various ways. The first is by manually constructing an upper triangular matrix. The other is by setting a square matrix with non-zero elements, and the students used the np.triu() function to create an upper triangular matrix.

In [22]:
np.array([
          [1,2,3,4],
          [0,3,6,9],
          [0,0,-2,1],
          [0,0,0,-3]
])

array([[ 1,  2,  3,  4],
       [ 0,  3,  6,  9],
       [ 0,  0, -2,  1],
       [ 0,  0,  0, -3]])

In [23]:
a = np.array([
              [1,2,3],
              [4,5,6],
              [7,8,9]
])
np.triu(a)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

##Lower Triangular Matrix

#####The lower triangular matrix is also one of the classifications of the triangle matrix. It's a triangle matrix wherein the elements below the main diagonal of a particular matrix is equal to non-zero values, while the upper part is pure zero elements. For instance, in this part of the activity, the students were able to program lower triangular matrix in numerous ways. The first is by constructing an upper triangular matrix manually. The other one is by setting a 4x4 square matrix with non-zero elements, and the students used the np.tril() function to create a lower triangular matrix.

In [24]:
np.array([
          [1,0,0,0],
          [-2,6,0,0],
          [-7,3,-2,0],
          [1,2,-2,-3]
])

array([[ 1,  0,  0,  0],
       [-2,  6,  0,  0],
       [-7,  3, -2,  0],
       [ 1,  2, -2, -3]])

In [25]:
a = np.array([
              [1,2,3],
              [4,5,6],
              [7,8,9]
])
np.tril(a)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

###Practice

In [32]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline 

###1. Given the linear combination below, try to create a corresponding matrix representing it.


:$$\theta = 5x + 3y - z$$


In [33]:
θ = np.array([
  [5, 3, -1]
])
print(θ)

[[ 5  3 -1]]


###2.Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.


$$
A = \left\{\begin{array}
5x_1 + 2x_2 +x_3\\
4x_2 - x_3\\
10x_3
\end{array}\right.
$$


###3.Given the matrix below, express it as a linear combination in a markdown and a LaTeX markdown


In [34]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])


$$
A = \left\{\begin{array}
1x_1 + 7x_2 + 8x_3\\
2x_1 + 2x_2 + 2x_3\\
4x_1 + 6x_2 + 7x_3
\end{array}\right.
$$


###4.Given the matrix below, display the output as a LaTeX markdown also express it as a system of linear combinations.


In [35]:
H = np.tril(G)
H


array([[1, 0, 0],
       [2, 2, 0],
       [4, 6, 7]])

$$
A = \left\{\begin{array}
1x_1\\
2x_1 + 2x_2\\
4x_1 + 6x_2 + 7x_3
\end{array}\right.
$$


##Matrix ALgebra

#####Matrix Algebra is widely used in simplifying the presentation and solution of a particular mathematical expression. It consists of different mathematical operations such as Addition, Subtraction, and Element-wise multiplication. How each operation works is the same as how the fundamental operations operate; however, the operation will apply to the element for element, just like the student's examples created below.

###ADDITION

In [26]:
R = np.array([
              [2,3],
              [4,2],
              [1,5]
])
J = np.array([
              [3,3],
              [4,-12],
              [11,5]
])
R+J

array([[  5,   6],
       [  8, -10],
       [ 12,  10]])

In [27]:
7+R

array([[ 9, 10],
       [11,  9],
       [ 8, 12]])

##SUBTRACTION

In [28]:
R = np.array([
              [2,3],
              [4,2],
              [1,5]
])
J = np.array([
              [3,3],
              [4,-12],
              [11,5]
])
R-J

array([[ -1,   0],
       [  0,  14],
       [-10,   0]])

In [29]:
J-31

array([[-28, -28],
       [-27, -43],
       [-20, -26]])

##Element-wise Multiplication

In [30]:
R = np.array([
              [2,3],
              [4,2],
              [1,5]
])
J = np.array([
              [3,3],
              [4,-12],
              [11,5]
])
R*J
np.multiply(R,J)

array([[  6,   9],
       [ 16, -24],
       [ 11,  25]])

##TASK 1

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline 

In [ ]:
def mat_desc(matrix):
  mat = matrix
  f = 'False'
  if matrix.size > 0:
    is_square = True if matrix.shape[0] == matrix.shape[1] else False
    is_empty = True if matrix.shape[0] == matrix.shape[1] == 0 else False
    is_ones = True if (np.ones((matrix.shape[0],matrix.shape[1])) == mat).all() else False
    is_zero = True if (np.zeros((matrix.shape[0],matrix.shape[1])) == mat).all() else False
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nSize:{matrix.size}\nRank:\t{matrix.ndim}\nIs the matrix square:{is_square}\nEmpty Matrix: False\nOnes Matrix:{is_ones}\nZero Matrix:{is_zero}')
  else:
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nSize:{matrix.size}\nRank:\t{matrix.ndim}\nIs the matrix square:{f}\nEmpty Matrix: True\nOnes Matrix:{f}\nZero Matrix:{f}')
  
  if matrix.shape[0]==matrix.shape[1]:
    is_identity = True if (np.identity(matrix.shape[0]) == mat).all() else False
    print(f'Identity Matrix:{is_identity}')
  else:
    print(f'Identity Matrix:{f}')
 

In [ ]:
matrix2 = np.array([
                    [11,32,9],
                    [1,2,22],
                    [8,2,1],
                    [1,2,3]
])
mat_desc(matrix2)


Matrix:
[[11 32  9]
 [ 1  2 22]
 [ 8  2  1]
 [ 1  2  3]]

Shape:	(4, 3)
Size:12
Rank:	2
Is the matrix square:False
Empty Matrix: False
Ones Matrix:False
Zero Matrix:False
Identity Matrix:False


In [ ]:
matrix22 = np.array([
                    []
])
mat_desc(matrix22)

Matrix:
[]

Shape:	(1, 0)
Size:0
Rank:	2
Is the matrix square:False
Empty Matrix: True
Ones Matrix:False
Zero Matrix:False
Identity Matrix:False


In [ ]:
m = np.identity(5)
mat_desc(m)

Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Shape:	(5, 5)
Size:25
Rank:	2
Is the matrix square:True
Matrix is not EMPTY
Ones Matrix:False
Zero Matrix:False
Identity Matrix:True


In [ ]:
matrix1 = np.ones((4,4))
mat_desc(matrix1)

Matrix:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Shape:	(4, 4)
Size:16
Rank:	2
Is the matrix square:True
Matrix is not EMPTY
Ones Matrix:True
Zero Matrix:False
Identity Matrix:False


In [ ]:
matrix6 = np.array([
                    [0,0,0,0],
                    [0,0,0,0],
                    [0,0,0,0]
])

mat_desc(matrix6)

Matrix:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Shape:	(3, 4)
Size:12
Rank:	2
Is the matrix square:False
Matrix is not EMPTY
Ones Matrix:False
Zero Matrix:True
Identity Matrix:False


##Task 2

In [37]:
import numpy as np
def mat_operations(matrix_1, matrix_2):

  if(matrix_1.shape != matrix_2.shape):
    print('The matrices are not equal in dimensions. Please try again.')
    return

  print("Input the desired operation.\n + = additon\n - = subtraction\n * = multiplication\n / = division.")
  operation = input('Enter operation: ')

#addition
  if (operation == '+'):
      sum = matrix_1 + matrix_2
      print("The sum of matrix 1 and matrix 2 is:\n {}".format(sum))
#subtraction
  if (operation == '-'):
      diff = matrix_1 - matrix_2
      print("The difference of matrix 1 and matrix 2 is:\n {}".format(diff))
#multiplication
  if (operation == '*'):
      pro = matrix_1 * matrix_2
      print("The difference of matrix 1 and matrix 2 is:\n {}".format(pro))
#division
  if (operation == '/'):
      quo = matrix_1 / matrix_2
      print("The quotient of matrix 1 and matrix 2 is:\n {}".format(quo))

In [38]:
K = np.array([[10.23,-8],
    [0 ,-2.09],
    [1, 2]])

P = np.array([[2, -9.003, 7],
    [0, 1.454, 3.097]])
    
mat_operations(K,P)

The matrices are not equal in dimensions. Please try again.


In [42]:
K = np.array([[10.23,-8,4.7843],
    [0 ,-2.09,3.867],
    [1, 2,3]])

P = np.array([[2, -9.003, 7],
    [0, 1.454, 3.097],
    [5,6,7]])
    
mat_operations(K,P)

Input the desired operation.
 + = additon
 - = subtraction
 * = multiplication
 / = division.
Enter operation: +
The sum of matrix 1 and matrix 2 is:
 [[ 12.23   -17.003   11.7843]
 [  0.      -0.636    6.964 ]
 [  6.       8.      10.    ]]


In [39]:
Y = np.array([[103,-8, 7845],
    [0 ,-287, 3.867],
    [23, 56, 9]])

X = np.array([[3, -4548, 54],
    [78, 1, 468],
    [98, 544, 5]])
    
mat_operations(X,Y)

Input the desired operation.
 + = additon
 - = subtraction
 * = multiplication
 / = division.
Enter operation: -
The difference of matrix 1 and matrix 2 is:
 [[-1.00000e+02 -4.54000e+03 -7.79100e+03]
 [ 7.80000e+01  2.88000e+02  4.64133e+02]
 [ 7.50000e+01  4.88000e+02 -4.00000e+00]]


In [40]:
R = np.array([[1.23,-7, 1.3853],
    [4 ,-12.10, -2.7],
    [-3, 1.09, 3.3]])

J = np.array([[22, -8.3, 4],
    [20, -11.45, 13.97],
    [-5, 16, 8.1]])
    
mat_operations(R,J)

Input the desired operation.
 + = additon
 - = subtraction
 * = multiplication
 / = division.
Enter operation: *
The difference of matrix 1 and matrix 2 is:
 [[ 27.06    58.1      5.5412]
 [ 80.     138.545  -37.719 ]
 [ 15.      17.44    26.73  ]]


In [41]:
R = np.array([[1.23,-7, 1.3853],
    [4 ,-12.10, -2.7],
    [-3, 1.09, 3.3]])

J = np.array([[2, -8., 8],
    [2, -15, 17],
    [-15, 6, .1]])
    
mat_operations(R,J)

Input the desired operation.
 + = additon
 - = subtraction
 * = multiplication
 / = division.
Enter operation: /
The quotient of matrix 1 and matrix 2 is:
 [[ 0.615       0.875       0.1731625 ]
 [ 2.          0.80666667 -0.15882353]
 [ 0.2         0.18166667 33.        ]]
